name: plant_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  path_provider: ^2.0.5
  path: ^1.8.3
  provider: ^6.0.5
  http: ^1.1.0
  enum_to_string: ^2.0.1
  flutter_localization: ^0.1.14
  fluttertoast: ^8.2.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/